### ISSUE TITLE
Software not working

### ISSUE THREAD

**Issue by PavithraPillai** [ShalmonAnandas/AutoRefPy#1]
I tried using this software and this is the error I got. 
Current browser version is 108.0.5359.125 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x00A969A3+2582947]
        Ordinal0 [0x00A2A6D1+2139857]
        Ordinal0 [0x00923A98+1063576]
        Ordinal0 [0x009433B8+1192888]
        Ordinal0 [0x0093F235+1176117]
        Ordinal0 [0x0093C9E1+1165793]
        Ordinal0 [0x0096CFFF+1363967]
        Ordinal0 [0x0096CC2A+1362986]
        Ordinal0 [0x00968366+1344358]
        Ordinal0 [0x00945176+1200502]
        Ordinal0 [0x00946066+1204326]
        GetHandleVerifier [0x00C3BE02+1675858]
        GetHandleVerifier [0x00CF036C+2414524]
        GetHandleVerifier [0x00B2BB01+560977]
        GetHandleVerifier [0x00B2A8D3+556323]
        Ordinal0 [0x00A3020E+2163214]
        Ordinal0 [0x00A35078+2183288]
        Ordinal0 [0x00A351C0+2183616]
        Ordinal0 [0x00A3EE1C+2223644]
        BaseThreadInitThunk [0x76937D69+25]
        RtlInitializeExceptionChain [0x77D9BB9B+107]
        RtlClearBits [0x77D9BB1F+191]

**Comment by ShalmonAnandas** [comment]
Fixed with most recent push
